service: nest-sequelize-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/src/index.handler
    events:
    - http:
        cors: true
        path: 'users'
        method: get
    - http:
        cors: true
        path: 'users/{id}'
        method: get
    - http:
        cors: true
        path: 'users'
        method: post
    - http:
        cors: true
        path: 'users/{id}'
        method: delete